name: census-exercise

dependencies:
    - python=3.7
    - pip:
        - notebook
        - jupyterlab
        - nbdime
        - pandas
        - scikit-learn
        - matplotlib
        - seaborn
        - plotly
